apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysqldb
        env:
        - name: MYSQL_USER
          value: shiv
        - name: MYSQL_ROOT_PASSWORD
          value: shiv123456
        - name: MYSQL_DATABASE
          value: shiv

        ports:
        - name: tcp
          containerPort: 3306
        volumeMounts:
        - name: my-volume
          mountPath: /var/lib/mysql
      volumes:
        - name: my-volume
          hostPath:
            path: /home/ubuntu/datavolume
            type: DirectoryOrCreate
            
---

apiVersion: v1
kind: Service
metadata:
  name: mysqldb
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 3306
  selector:
    app: mysql
